# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lifeBalance' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for lifeBalance
  pod 'AppCenter/Crashes', '~> 1.3.0'
  pod 'AppCenter/Analytics', '~> 1.3.0'
  pod 'AppCenterReactNativeShared', '~> 1.2.0'

  

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'lifeBalanceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'lifeBalance-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for lifeBalance-tvOS

  target 'lifeBalance-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
